title: Dong Won (Don) Lee
description: Statistics and Machine Learning Student @ CMU
site_title: 'dongwonl'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: dondongwon
# blog_url: https://www.nagekar.com
email: dondongwonlee@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:
